---
glitchtip_backup_mount_point: /mnt/glitchtip-postgres-backups
glitchtip_backup_schedule: '*-*-* 03:15:00'
glitchtip_postgres_listen_addresses: 'localhost,10.0.10.83'
glitchtip_state_dir: /etc/glitchtip-data
glitchtip_redis_bind: '127.0.0.1 10.0.10.83'
glitchtip_redis_appendonly: 'yes'
