---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    cloudflare-api-token: AgAICghzopgSviHZOw8oGUsg53A/GrzOEzMPlpWzg0bu0xfZzrrLQxBhFqLvwwyWfeuHJa0ha7iF7kAIcDc5zsO2nitsAJYkKDAm5yVLUBqIkMmgs8qcaxzuknFpGPEwd2OlpgH04G7COSW8BK7B7DkbjWcww2ije7VVU1Osj7saKRzPLZ4+WxlIYRqmxsVSTfkJjszCL+7Yamz6qoYXb+VrMKxCDOR7YhsIqtlFh5pvP1iEvu28KQPRwYAuSVZKwEunvFfi0b+jycIJwOJyz2VT5kgYWKC6nQIZ/SvqPLig5Y+bBpwhDPWxhk++dpii+Xvni33EOrx3dNQfBXfAaGAO7nXohUV+D64k37Of0NwGt6FhrOkl8j60e1+vLEgMzVsXc38LYM56SarsV5ciPVhFrDOTzzGCc+mb7KepXC3o59rKY8lpfZLlLP0Old5Rq3uLUL5bULROtdQMuzDwqWd0Z4FIH70Tdn3bESJVFS5RA3B0sD4T49mPFcYouV/UM56IeRdug3641EjxxhA+x1seXp0h9oKh1aT8jTY5VJZmC5lTGhUC7v0ISAJN28JLCePIvBfaXKcfLjUiMeTgamdRtXPjR8e6BuGuz/+uHTQG2p1DLm5ECv48+OBHKZpHtXisqud2N4XkwW4/Ycm4cBwsYPK00sn1cDjzJ98POlTrltSeKyz6VA+IrDE3PC52c66wmUZDGkCHN9RNXTyEnEH4SxE2/KsaoI2kGVwSjDxYsaaYBXNh186z
    email: AgBAAIljVSwpIv4/pFso8U9l+nRdGrWyt1QpnObgQdQNdPaRZDUCTA9ngLWvMCpLy1YhC87mYpsVtTdYswURGho+nUXmGkc1Paj5KgBR2gu10lrZqzWO8dhhSsJ3AL/JzEOYJKlP7gXcTWtZ1UKzqgVmFKWPKDxYFbXgMVpTR1Ukc4z/iu7FisdtsvcZOM3VPBbOJRKdVWjs4u6rHxr3so4c837i6/xALyef8vXFpmH5PaQAeLLj8hVBhxy5mNRbbmAIWFRFouzhmjbiIHlNSmAYZrkP4iXMJYgbMXLKTCCsh5WmbPOGuH9WXNYRw4jjZOG90nYqOdzsSQ6D0SCS+H15nZzfThzX5NI5S0rmyT7EAzaUlJoDWYLpiYFUMWTyS5UVLLinfcHk9rcgOThyhijE/N8TAQ0QeTctwqYhz68U1uonfvFikEhRXIdPKgwHg89iNQBgChF2vxf7rFQcIdMjWkLAxAfs6exsvVifRjsvIPxud5phO7WQSIUXUO4Xuo3/vxqOOQqX9UY0l1Ox/mmMSBG/pLoggOtFVQ/LTi+49NTMk8AQ3M7bwaEfW4sx67DhLUqURpDEPtyxJloVolvtg3vElrqTUW3TePbYEZ4h5u3FGYKTocoULfXijQXohgmU4VhqKHiH5ShhSG4wX0FZYye046BrLMruaTOr/8fMpFP7XmDQY2rxGjSPQd0qKVGGR609aWJAy4aAjAa8bV83LqA=
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque

