---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    cloudflare-api-token: AgAOjsPXapRJkj8XSF6uP7LEqGj9DdoQMZNGLITVs3bb/UTEnNkuo0NmzxPdYmKS9p3cWNJT8Du4CIIsO6g3w72oQOgR8lU9Nv0hBwSwUKZ4N55gvuq+DzVChTVDk65BKyEU6jCVFyczisajXmrrAFHN6QjAZHnaBY8btTFxS7Mp0Z8Lo5KNq8Sr6/bKwcZ8/yCTT9N09w0CFMrtW4BkKNuEqHo/Vd87coUU0TesYbFi1D9uVZyZ23n7gukcE6lSENN7Cl1kZPOGpuNwqjPsBmpUHYVngqoiWm3EN+ijgfqYHTugr6ydyHCIay10MogmSeTcnlaq8ee9eGWDnkb8BGHMURedGlOAMISCygRQfxVNHrRxMmH2cNQ+jHSmWxw0VrKd8ZVOxlO+OYKmk7OEndNXFIG/nEXnikoH9UvwSh5AtinW7cFGipkBDboULYdJe6tPRey6VFW3Qhe87tuQzh1BUAOQoPkk+kLSTCX7/0n+8QLrp1KEiuEndLoEL72Y/YJzPSa/uGwSOst5akOQRMmqPEjhMrui+gBWczYpSxT8f5uuH6eX+g/UdzTtK4ICKk0hi0fNCAWrSPItA1YBw8xmX27+AlWcmUWJneCKZVe/Grdxa0sdU6g8rx5NUg7NDT+2XBfZQq0pNuhcXw67dWPf/bVKGfocoSA/rVKqh5c3xb62UEXns4TYW8IsQT5BOH65YwuhI9MVgOGezLmJ7iYlYdjspZ/8lPfiiL5HdTK7d4EPjv1CdiZE
    email: AgBTHXaIFu47fmsZs/jK5JBy6lq90O5Q8VbAx3i0H44waBhmVnAVZJy8SMJ8FAG7OzaRZkjHEgJAP3guLCIipyAmA96oFopbAaPVDGbMzl6tTnxpzSv9X2hp1EmjZ4etXdJyQAdOogCIy55E1QfbyQGdt/TeeK+C4qlSxql7DXrnin3OxoafHzOsZp/vDmOyD7p1f1M/22kNuqtMBI5E8p5/DVXD1gobLY+eK91sh/edTC/Ilr7Dlf5F75CoLeEt+jvgX3smxJpC2dxLA2j1WY+0ZQHKsakvsPauq46/4EQxGyCbQARSHe6sf1TLGfRBR+VawYnf6O0hZr95/yw9sjszHTU/F3kqvlj7gincsPyju/VaJw+OjOSlPtk6wq+f2IOqp2vpnpo1SMtewSKWTqKa8N8WvoK7uaGeDQB2bP0hX2qRPAJ4qkqs4ZRdziH0R+IKyKntpy47oCHTMMFGVR6YnhyOiQCL+1fjtXI7fXx6HGjSU+nwjJrKTVcE8jVdH+gJ36zcXL9Wl63Av/8ruBStTT3VJGg0k31GKDQfwPPHHZXnxT2wY7e1eQmiTPKoB4a8rKnDW7PIR5rNvb7f0yI8heX2r0wsVtlT+qwQIotOJdMTnfkm9LgN95OuVfqu0joj1HuEJCoHhDiyb95/coNPhTemMhy+ABCCA/YKkMJoLeQLgL9mxrGgltS89PNmtnKcGwGMTcEbtBsxda1XO17E5oU=
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque

