---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    cloudflare-api-token: AgA3HyR+JACDo3bqlkAPflItCYnNJaaEgXW9h7t3XMynjdE8Q6oL5n/zKwEsGhHWV+Wl70xE1YDfMszq9i8qT2dyxobN0h+vk1Qo7h05xalJ/PYhMlh9MGDpkdRXj6WJGMms2S4AN2NCOKdnMGC1Mu+NrL6ehc/nwfwStTZvgNFpS3qaxO02OZKt1PKMFSwpvU2mkyQnkLvCwBkR3mxzjYRUxel73wswXYRSEZe12RSzPc9C+AmrPCJner05oWzKv4eNz8LMl66GeA4w3EN6N4Pku3ksWHLefFEZ7jbBlLcual/g/IkBeTyuM/DVs/GYowqOZsF7bcmsf4fLCUTaQUWD6nxV1B4Fdc+fTCbhbG3jF8+r9Dmv+50K3j5Peil7H9etDWTmSU0rbggAakWPGzCs/Kvboa1ki69YMcFyI6CUVmyWzbIb3dzdMrHr2h6PoU8NZ2/sEkjawE8PZ6Vp0d675AxCpmvnLOAVzEX2MXZgWV/tvfQlhwYEatowg6hWyCatZ4zgCzaNtoBePvlRhxZIanjnRZbUuHW2x2s3tkTlUOVHGkjKW5+hsM+YBB4M4tg8fC33uIE51GuzAgjmHVeJcSTWvAuMbg9m8qTgrmsM8OXuQV3DMEBRbGebnMh4gohy+becMmngfn2LzQRZadeSeY9dupsnFQFW2oycjvVDr67ROKTj4eISrvdq69QE9NotRfr4NW7rJz/uTSrpF6bPxykeWFNRPJL7HX9Kxm/Nf9n+fuaZ6OSb
    email: AgAlb3GVvxy4BwZAlWf53MZzIt76i1735eArtgMrZhCti6OjoahvK77timIECgiZjXzLhptG04duYy9JFZ09agUbntMpp3HoaqmVbp7w4OV+jEtlFTLl1rJX7yXbDNu2ZvT5lB6E33ZTQog53tOuU4mZDrJFnouKl2YS8SYvcV9tFYFRT2zjs35gg9YM4Z41CMeb+I+rvd7aWJq1PL/kMmJRyLnu6v2sONrmccYd4Hqr4J9hPxCn4PzZTDZfe2vXQOMY8Wjka/wOKYJuiMBIAmI6ijQZbg12mPJUpfR2EtiBkjFiv0ezF0JlrIir73j2nE+Rzs9QeTtCsbBIaTnwJq7YYMzC4S4fIUZ4igACkzC5kpi0Ygz9j+TORMSiiKxrKtdvufKncRBaoKZ1Y0JZud1kK0hd3pEi+sfJ4KAHGhuINM7SoOI/g1Fn74Eg5Yi7OA8gUQfXtaxBsaoDYQZOLYWHOYCGHppH7YFYqkGb5ApzrkWQewJ5Hyqwqd1DkIHOERbR2L2gDFulIStbGBFIeOFJgIiK069ywj8RFwSZz1Gt01QSFTCiZgMCqaxsh3GD7uNQ7Buo/Yto4Kv2C3IAFLw46JKcHhpLFXlTiAlbARuIzi9N3F7zstIcfwzd2IuHyWJQEP79SqomJvzO//0QGY/rPyTIyDM194P8z8KlWGt+TvebehjGWuxeAS43pCZqjXZ7N27AXs0vOIfzFCJAaNEBF1c=
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque

