cipassword: ENC[AES256_GCM,data:JZyrd4aZXKpP,iv:dYRGK/N6WUuaOyEtBV2lxUv5vvOXSW0R53iTvSGk0wQ=,tag:rTlitncj2G2tawxwxnqkqg==,type:str]
sops:
    age:
        - recipient: age1n5l0gxf0mjdhnpq6v6dx22vj7lctv7xsyz5eyf7ktq8284rlhs3speeycx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOZnNZa0dFZEpxbXpZWC82
            bUJyZE9ZeTJFaVpzNTFrQXNaeERXNnVpWmhvCjFTN2V5Z0ZyWSsydU9DLzZkRzYz
            TDFxVmZ6VWcraXY1VjBsMVVLTmVSNkEKLS0tIFMwNnVhS1ZNVVJ1anJzRTV4SFBP
            KzBOUEozVHJIYlpVZ2ZtWFZrQjQ1Y0kKmGGn4qGwjAfNS8SvHuFWpiz6rTa3UBOf
            rD1vw+z7DTrkkAWGlT5/uFlmBnptQ8LUUsAz5Ph0BHU5EThM41UnDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T15:17:04Z"
    mac: ENC[AES256_GCM,data:NTaf4F3Pw4ukWrAxf927FlmuWXr6XlX7LSx08soDxvUpLJqdf7o0ouyjwKw7o9V8FBYgbmggqdcI6EuRAmyE9hsf4ltah2I/MmAuSEl1/7sPo8OtZ2oMVhNJx4spv2FFNG7E8KB45ypnG1cOAeMHPL0cmB4a3ZybpvcS+SMtGQ4=,iv:dB7PUp/cbbrHtrUolpm+uPRO0ufHfYo9MB6J8wDWG74=,tag:JxVpFsmgHLyMIcBS2WHXGw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
