---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: glitchtip-duckdb
  namespace: glitchtip
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-csi
  resources:
    requests:
      storage: 20Gi