cloudflare_email: ENC[AES256_GCM,data:QXUGYHegommjq5ecDOETByl7,iv:ORoofIGt8Ez0/+m4XT9qVZMV68bgIDqjc4Fot4FB80k=,tag:cWH9TE59bm/XLt8H54oPrw==,type:str]
cloudflare_api_token: ENC[AES256_GCM,data:5jpUrgUvIqys2SqtJsU+BT1rJSDBhYycNuC2r6WBF+89lcZcWSc4ew==,iv:OYHuYPY1sxxVdpcxoa78Bnaaqjgr6jLK0h7ZZsGdyZM=,tag:+LyCpLiq/Mv6wNnwrKvHUA==,type:str]
cloudflare_domain: ENC[AES256_GCM,data:+6zivvLPmIIjlVg=,iv:iqT0KnMaWRQppQKBPT6agjHLkEmDX3cBfSxDE2+kCJc=,tag:cYNAVy2F9iAaEFLDWAlPvQ==,type:str]
cloudflare_tunnel_name: ENC[AES256_GCM,data:XdTPgVCeylFH7g==,iv:quxGKHEPgMh0ESgWsUsL3pkDIzWxhmWtXX/u8YuNpCY=,tag:zVdr1rbw8e7uLFkzPtZyQA==,type:str]
sops:
    age:
        - recipient: age1n5l0gxf0mjdhnpq6v6dx22vj7lctv7xsyz5eyf7ktq8284rlhs3speeycx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrc1VOSEJhT2hXTmI0VWxt
            d2F6TWg2NWlsM0w4UERodEdXL3VSQVkxQlJJCnFvRDZrSTJRZWM1RkxqTnVabzVl
            eC9FazQ4MExzZFgwRkVYaFhxbXg5cUEKLS0tIFd4RzAyVFpLYVJ5YkRBSkJ3VUNw
            cVJtZ0RsQmgwRTI3WklFSmNyNnF2L1UKXhy6EBo29LbVcZ8nEvQx9MmlUdgTq1P7
            2QnYJvT27IxcL6w1c2yqVdg+bYIwL87GkxHIjnq8ehq7xr9FKQNYSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-20T20:20:58Z"
    mac: ENC[AES256_GCM,data:0skiGAytJxx1r0WrKxyxBf/3vwBeP98JVY5Yux8itSAxW/IeUJ3EdCto4c2N21FaELXGm00qqDSITkK50GTw03F6B9+QP69jxsEVvH1vkVw3DioJxFZ4dkRCv3kBZmzT3Q882y6giXpPTgjmrXNOX+1UfLys9dLSSmZEDmdsjlw=,iv:6JO6XDI2T4VJbfvMZauUcxO3qz1HtF3j3hru0CNC570=,tag:Isoq4AFRYYjAzmcUxGOZGg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
