---
- name: Ensure cert-manager namespace exists
  when: inventory_hostname == groups['controllers'][0]
  kubernetes.core.k8s:
    state: present
    kind: Namespace
    api_version: v1
    name: "{{ cert_manager_namespace }}"
