---

- name: Restart postgresql
  ansible.builtin.systemd:
    name: "postgresql@{{ services_data_postgres_version }}-main"
    state: restarted

- name: Restart redis
  ansible.builtin.systemd:
    name: redis-server
    state: restarted

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart victoria-metrics
  ansible.builtin.systemd:
    name: victoria-metrics
    state: restarted
    daemon_reload: true

- name: Restart victoria-logs
  ansible.builtin.systemd:
    name: victoria-logs
    state: restarted
    daemon_reload: true

- name: Restart garage
  ansible.builtin.systemd:
    name: garage
    state: restarted
    daemon_reload: true

- name: Restart tempo
  ansible.builtin.systemd:
    name: tempo
    state: restarted
    daemon_reload: true
