---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: grafana-secrets
  namespace: victoria-metrics-stack
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
  labels:
    app.kubernetes.io/managed-by: infisical-operator
spec:
  hostAPI: http://infisical.infisical.svc.cluster.local:8080/api
  syncConfig:
    resyncInterval: 60s
  authentication:
    kubernetesAuth:
      identityId: 3faa50da-6467-4568-aa22-da12507306de
      autoCreateServiceAccountToken: true
      serviceAccountRef:
        name: infisical-opera-controller-manager
        namespace: infisical-operator
      secretsScope:
        projectSlug: the-lab-kjtq
        envSlug: prod
        secretsPath: /kubernetes/grafana
        recursive: false
  managedKubeSecretReferences:
    - secretName: grafana-secrets
      secretNamespace: victoria-metrics-stack
      secretType: Opaque
      creationPolicy: Owner
      template:
        includeAllSecrets: false
        data:
          POSTGRES_PASSWORD: '{{ `{{ .POSTGRES_PASSWORD.Value }}` }}'
          DB_HOST: '{{ `{{ .DB_HOST.Value }}` }}'
          DB_PORT: '{{ `{{ .DB_PORT.Value }}` }}'
          POSTGRES_USER: '{{ `{{ .POSTGRES_USER.Value }}` }}'
          POSTGRES_DB: '{{ `{{ .POSTGRES_DB.Value }}` }}'
          GF_SECURITY_ADMIN_PASSWORD: '{{ `{{ .GF_SECURITY_ADMIN_PASSWORD.Value }}` }}'
