---
glitchtip:
  image:
    repository: glitchtip/glitchtip
    tag: 6.0.10

  extraEnvVars:
    - name: EMAIL_URL
      valueFrom:
        secretKeyRef:
          name: glitchtip-secrets
          key: EMAIL_URL
    - name: DEFAULT_FROM_EMAIL
      valueFrom:
        secretKeyRef:
          name: glitchtip-secrets
          key: DEFAULT_FROM_EMAIL

  glitchtip:
    domain: "https://glitchtip.local.bysliek.com"
    existingSecret: glitchtip-secrets
    existingSecretKey: SECRET_KEY
    database:
      existingSecret: glitchtip-secrets
      existingSecretKey: DATABASE_URL
    maintenanceDatabase:
      existingSecret: glitchtip-secrets
      existingSecretKey: MAINTENANCE_DATABASE_URL
    valkey:
      existingSecret: glitchtip-secrets
      existingSecretKey: REDIS_URL

  migrationJob:
    enabled: true
    database:
      existingSecret: glitchtip-secrets
      existingSecretKey: MAINTENANCE_DATABASE_URL

  web:
    replicaCount: 1
    ingress:
      enabled: true
      className: cilium
      annotations:
        cert-manager.io/cluster-issuer: cloudflare-cluster-issuer
      hosts:
        - host: glitchtip.local.bysliek.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: glitchtip-tls
          hosts:
            - glitchtip.local.bysliek.com

  worker:
    enabled: true
    replicaCount: 1
    database:
      existingSecret: glitchtip-secrets
      existingSecretKey: MAINTENANCE_DATABASE_URL

  valkey:
    enabled: false

  postgresql:
    enabled: false

  tests:
    configuration:
      enabled: false
