---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: arc-github-token
  namespace: arc-runners
spec:
  encryptedData:
    github_token: AgB7gd6jBV4d+kAvxgYJwlisrih3Vy3fU4NgV4EU7YgXqQ43LFK4+jm5ntC86zwCnXoR7SXi1t7cRR9NpUYZeQKiaJw+Y+UnYKRMX9vxxqQB8owyDni5M9W8jzZEx9qorwIdi2rQu1JGornJUAO+/sCusbsWFej0Izw5ZaLS3dBFBVZPPrUrA9BLK/yNcKVRiTtSb7/1IHCwr5SEdZ4U5CGX0cQZ1IYBMTHzOKWvazgk+rZG4/0tTB0FwHshWQPILOk97nEanFSxhZQAo6KRUFtdwpLnmr/8JXSDdPSEFtNK6XqVFHr0MNZCdiz5w0ALOZpYo7Tml3P5f1XOIeDQ3eyUa6VMKzUHjAx7qy2w2vTCPwEaa51Qc44qDdLdfYzJkIuhrPMt+yqmDd7gIYFzVTEBo8WKKFU+2q3XaRgAyNBq5y6xQ4m0RvVq5RZe82JJZaafIgzC7rlpkrnH+L2FzgDmQVnD3GwuHMzqtzB/dNvBrRIza8czXUkmNGMVXWQb3hUcp1QTzlYwkFK4xS2YWFeZP5ExyeUsUgcnmfJUTjBPhqlUSQdPz13faYS5PNV8zMg3WsiYulorw0hyh+TymCdFKXRp/xu3N83Vzpc+HqiTN5WLx1gT8Ua/BuZOR6Xe7NantooKgYlmNVY6RfDG/CAXnvdaiB3l90k8yd22gSc0fMU3P7dsGE/55DbGV0wwXAAd46MUr61Ee/9G
  template:
    metadata:
      creationTimestamp: null
      name: arc-github-token
      namespace: arc-runners
    type: Opaque

