---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: arc-github-token
  namespace: arc-runners
spec:
  encryptedData:
    github_token: AgAWquEtZ+n4jEDZPugUch/Xlm74R/RB6b25XG9iggKYSd7MGK/4+VkMkFjRem3ffNVAg1Vao8kQPYE8mxk7Ug7RwxwPLxtq4vhyJvmLc/xYH5TCYUe3Jjpj7eotk6zDDRoCYuQFQghpI4sqlCoP7EkVqeKwN3UstbURr6CCNgG5Y3/xE459FQIb7qO5tCg76iF+f8b5UVGHwZvzKrBWLY1MUJfTEUkBkzXoKZUrhtj8L3fmUU8EzcE0rq7ZfTceT37RauCB/BhMfyG06Y7KAQCoUNEfs35GY95FgafWG44STQyI99lrqZo+2afRJnp7IV4c7EIse4Eb957sl7HZuJ+Uej3ILA51POTC4cOLuYosgVvzz4TirY4nVjGU8jnRXUTAgZtfEXtJJ5vd5AxPV1Y/tPXHHMn8K6DlrnI4PMYvzhyuX+f70u6/urqAFEbJTxYN1aVBPh4+UHsfCJvN73MMe65PYaIG/qQZaYhATZkwohTEEMI2MYGwDef+txOlRzMZOuaup4zFgGgS1ZNBu97JgjK6xg9D0rD8QDvGDwe1u4heGuTPCD2OYPeUWOGSuP3D6gfugTcQXjuqhVsoF9Lh2CwE/MWdiGv4orhzx/padCnuxkrQROCp1R906SyJiHv6zjukhjizdUZibEvHChK4FVRmtCjqCKhI0btqnk8VPtMJJ1Pu4CIupLqDYVOwsmcbSvhGXD9TAwae
  template:
    metadata:
      creationTimestamp: null
      name: arc-github-token
      namespace: arc-runners
    type: Opaque

