---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: arc-github-token
  namespace: arc-runners
spec:
  encryptedData:
    github_token: AgB4J5KUQ20n/JRCQaTRCD8ntA0sqfL2apmF36R+gyP7TcifzM4CYvCBh6eqFOQpBhTBxKCbNS0WI/jhw0K3TDGc2Ka4qKi22ue8tlLcLEblLgNE6SHb+nVyOBlzwzH2tBRZOZ93E4ehUEfVtp+1Pk4PLpWvmBzKXkG2SBXsKlH+QGjWrCSltlMqsWIK/1VCIbB0Qm8RGcibjn73rsXZeG9ae60cM6doWvQLAK1sBr5K46wDxHZtUi5PVOZKwg8c1F7e5p4VOikzy2LY0f7j+9Z5RcgMcE6Btp9XwkIJ8sddUQaOVdIrRiwXJlu5CgYfbYHtlnEQP9ZMK8NGOhzO0dvAASBOTkN2cj8dBk2JK4l8b0KsW/QDcijPcW21GwtMRAMjlLei1Ao6aF9g1DXKOE2++TDzWt/Cro+GvZOYLn7y1Ua8Y5FOGZNAvt40Tmff9BFKsR5+5qb98DT8x8xgbJJUQl0Uu+lqfjZF/LQPmOdftLhwVB0BayZoo3r0yM7TSY9aJKvpmNMfB9WY1CpSgSga7AowzPE9K+4g7hLAaZ0o36kOrSLnHj0Zst98q4KtpGwMfrX0stAL6rVezScZLR9oeVV3l/lkouq7gEe+JXoVXBukwh80tLfRWJOpJH+UsBM63+FH4VvFKfKebW1ZiJEVHoxPy89RgfQmJkHjiuk4Pyf/QIvpTId1yVDeSbvUhetN4yNXxmuz+z7Y
  template:
    metadata:
      creationTimestamp: null
      name: arc-github-token
      namespace: arc-runners
    type: Opaque

