argocd_domain: ENC[AES256_GCM,data:AvzdbaPoCiUGqSrcQP7+38qNhuRQzJoK,iv:THLqcCxnOC9mSjIforSrngBYZ16UDr/SEZiWdhWzkq0=,tag:SgVIPszMSOuSgNvoj1arHQ==,type:str]
argocd_chart_version: ENC[AES256_GCM,data:CSX6LyE=,iv:szqTiwR1LW2SU5zyBNNjTPsHOIzVkZbXC+se50cZYXQ=,tag:Tswq9VX503iYXldzZ3E35Q==,type:str]
argocd_namespace: ENC[AES256_GCM,data:iBUSR3Vx,iv:9nH5eORAjCINmbLe0+S6WYQNR2VPG5zyUJIajbqj3n0=,tag:k+jsF7WnkMEMiPogtFtuGQ==,type:str]
argocd_insecure: ENC[AES256_GCM,data:G5DbMkU=,iv:bioT4vQSC0sCjRg3aDc4n5O/MQ5ys6Q3J9ha6UevZRw=,tag:CO14Kj4uakPlfxc7JLCPwQ==,type:bool]
argocd_admin_password: ENC[AES256_GCM,data:g7l0b3meJ/aczRw+AsDGif2AzN9PMemL1Wo9lmj+pL35bEpLfZ+ygj3gxhOjjxYGMTAERaUcU8gOVw3E,iv:hKU43MgVXr/f1bx+8imOd27gaCldgn+AF8EaZndlGs4=,tag:ku0AWHD8sAyYea8ReqsHCQ==,type:str]
helm_secrets_age_key_secret_name: ENC[AES256_GCM,data:QhcRUMernc/XytFKDS5F7USgtpU1I+vQOw==,iv:oAgZEZx6LBi2TxJTwdNWGpq4wLPp9bWPdDm3++rhErY=,tag:Xb6VNyiOXzPqXSMRmh9XVg==,type:str]
helm_secrets_age_key_secret_namespace: ENC[AES256_GCM,data:tPtr5bDg,iv:ZIC7Uh5d8EtUrkrlV6zrYysHyb8Kfz1TDZKBojVMwGM=,tag:mpOw0sauVBkwKpMIWwhp9g==,type:str]
sops:
    age:
        - recipient: age1n5l0gxf0mjdhnpq6v6dx22vj7lctv7xsyz5eyf7ktq8284rlhs3speeycx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCV21JL0ExOE9EeTNFUUM3
            Z204MVlSQjZFMVhBLzZ4OWJlV2M2Sk01SFdrCjNZYkx1OFdLaWxBMDRZQldiSEVV
            eWRpUGFHSzFUMC80aG9KNXVyQnVCdncKLS0tIENSS214V1FvWVJBcFRQSWVKV3g3
            cVdtMGViRnQyQzBFTUZ5dVRPNFlPRU0KF9Ja9dcaltcTyLv71jKS09ikOQ1Kk5d0
            bcPq0RepinfdeyrwKMHmqW5Gdls47mKhDe2CU5y8eOgEJoobxne19g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T15:17:04Z"
    mac: ENC[AES256_GCM,data:sUQNl0+MWFd6CQv3T07XARSE89gAmAMS25KOk2P+ATgz3etC+Ri21SQk8L3Gby5UsTOmq33AhKm8YMG6Mf/517yoPnDaWxfd01nx6+U3nF2ANTByzYsCFAt+YbM6dWpC4AtvMA7ftLqRFJls0X+vQcA9Mv2RDg1fSRCkg7zb5Ro=,iv:0ZTvCbG7cuphfpJTvb994cm5IXUtK8nBkNZxp/Y0lmE=,tag:aAfMa7Yl+LWNSNSbVYB8DA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
