argocd_domain: ENC[AES256_GCM,data:bnOZ6VBA2WKDSsNYG1mEJBm30rzwGENW,iv:ZFnXs+JZLpDF9+Ut+rvWlHwW2X7aTyf/ddRNZmh7tj0=,tag:LHmo820UaDqL/zr7k1PeJg==,type:str]
argocd_chart_version: ENC[AES256_GCM,data:KO7gQ54=,iv:xyI2AIK+x/0aj/KKHzUXHrxoSMA5GctJJax0NYObxh4=,tag:7SSnnme4q5Bx37weI6/hAA==,type:str]
argocd_namespace: ENC[AES256_GCM,data:nab1b/cd,iv:qu9xsqAHAX8jB6WC3NxZaONwUab+A9oopuLjdrjUjJc=,tag:KEJsVTq5QTbxj76F824xVA==,type:str]
argocd_insecure: ENC[AES256_GCM,data:2ST39R8=,iv:NhHXTi/XwVGvti153QOzjk6Z5m52U+zWnb7+BD+fAxQ=,tag:224V5ucOZeGE1mbQDFma5g==,type:bool]
argocd_admin_password: ENC[AES256_GCM,data:5Cw0XyMYmhIxT8TjZQxS7eJHfQmn5DiAFeFVWXUaidZupBTHCe1dWAXs1FB+hfts4XPR3l4Gj+OEKB82,iv:4oIbWVodiJhQy3h8xiCCHoEL/EsTTlWcwv1SVNVaRdw=,tag:o8CkOvalBmi1//ITpGZHHg==,type:str]
helm_secrets_age_key_secret_name: ENC[AES256_GCM,data:V69/KwocSOxGJwUlIFHTykwo44L+lcn2qw==,iv:arVRnH/knGJbWXJniRP6DghrmMrAdeA3HlTT3GmHf5k=,tag:eaAJBv3Pew+0SohkPTlgrg==,type:str]
helm_secrets_age_key_secret_namespace: ENC[AES256_GCM,data:pgaa+VLd,iv:bTsoQtA758frEWGylyMT7TYv4bANSJoM69R37QcRUso=,tag:Pgghxo2ayil4tgGd1eIqjw==,type:str]
sops:
    age:
        - recipient: age1n5l0gxf0mjdhnpq6v6dx22vj7lctv7xsyz5eyf7ktq8284rlhs3speeycx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0NWNabGFDU1VQcEtSM3Er
            ekJ0VWJEcGZvYmd1VDJTUGVuZUppYjBqZjA0CmRSOHVIMHZTTGR6QjF6bjIyb2hH
            YzhFc20rZHJSN0dVYnpxZXUrNHlLNW8KLS0tIHNSUFRKWklrV3BmaG1lWjhvdGo0
            VmtGdWpuUG5uc053aWdSWklVWTlmVTgKr07THViaTjR3YNT3z1frizDcgL8n/xeP
            3gJ+oMi354dOXI1mq1t60dmy20djsxFEYp0R57V7dGlIyw/EJKgnbg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-23T21:36:24Z"
    mac: ENC[AES256_GCM,data:IZvMZyxWtZIIt87gWO39ibOZShXUOWWDOU/uwqGKyPs9q0/MAuTSZpQZtSI+D9BarwJDHqsrEmcmsrwibtEhSQw1Jkidp8xw15qNzNC9+UoDDQbsWT+RVWamQA4XGIUHB9/ejC4drbYqisTIv+HuFIuqXSRJPWPtetEtmAUsubE=,iv:+kURBaacJ4m3U635o2roZSPWgftCPi503fPDV748LSI=,tag:MeL9nzFFVFIPsWgCjW+0hQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
