cert_manager_namespace: ENC[AES256_GCM,data:e8SigIOPAUFugRkx,iv:F/qXbVKH8jnatoL8jhVvjTfl45pE5RG7+jL19NT+uLc=,tag:X+FHqaO00tgBvCrSjIXCIw==,type:str]
cert_manager_cloudflare_api_secret_name: ENC[AES256_GCM,data:Oe7kQ9DKKiuwvEjv4Dd9smede8g=,iv:J2pIL0DknWhZyuL7N+/XhDrJNIKZl0nHzWstpPBacvw=,tag:v6JoT4m8NgXvavOac8LmKA==,type:str]
cert_manager_cloudflare_api_secret_key: ENC[AES256_GCM,data:YmMKyeUJxqi859T5bMcxwiCg5zo=,iv:yQlF1ITM5F6w47hU6h2b3mVwKMTFfZZlvNjzhG/5ndE=,tag:QegmfCLY6xlm+zRbCFsAZQ==,type:str]
cloudflare_api_token: ENC[AES256_GCM,data:tqgktTUicMQijAAR1EYbTOQAICh0W/oGGaPp6ulhQu5luqtkd7CQuQ==,iv:3ss/MhPlZoLLt7C8PQecS0NrIyZG2usqnf3cdR6VDfw=,tag:C23ZjpJbkh5Djrs2yokQbw==,type:str]
sops:
    age:
        - recipient: age1n5l0gxf0mjdhnpq6v6dx22vj7lctv7xsyz5eyf7ktq8284rlhs3speeycx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnVlBnL1o5UDBLSVE4RDUy
            WlBtTnZPSklyeXdpaW41ZHVpYTI1OFFlUVNVCjZweGV6K25VZjhtRlpDcnl5bEVl
            SnRLZnF1OWYzK2JublBNZ2JWQUNMVk0KLS0tIEQ0ajVaNjN1U3JXSktTc1pGZWFu
            NVpxekphNy8wWDg0SjNSU2R1NDdNQWcK9T1GpdQrjsvV6W+iE+jXGZHnYcVo8iNt
            VwGUJZEgBGBXPSShAhH7zsrN2/nfg2WlT7jUz79eSYdJJCCfmxLw3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-20T20:20:58Z"
    mac: ENC[AES256_GCM,data:aV8gICn/jaABBxJMnPoPoPcdD5FgWaIiMfrP9zZfNqKTb1/hxT3R3BYdWm5xKfogPC4uLjG82r/mhgDa3+0AMeSxhqTyMRMUeAYEQWR/sTvtiRa7mBdOM5bQOl4uTYPQ6LgL/YxyjIIZNUEex/CS8jxyUGOQDac0gyEy0SH0hvU=,iv:hej5JWOY5hnnOStCuUQxDPXWdZ0vELzdyEYJek2TGMo=,tag:VjK/LQSmjCc5Uyya87So5A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
